### ISSUE TITLE
onion_request_get_language_code leaks data each time it's called

### ISSUE THREAD

**Issue by ofiala-a51** [davidmoreno/onion#255]
I have discovered that everytime onion_request_get_language_code is called, it leaks a few bytes of data (length apparently depends on the length of the Accept-Language header).

Steps to reproduce:
- open examples/hello/hello.c in text editor
- add `ONION_INFO("%s", onion_request_get_language_code(req));` into the function `hello`
- compile
- run it with valgrind (I used params `--leak-check=full --show-leak-kinds=all --keep-stacktraces=alloc --track-origins=yes`)
- make at least one request (access 127.0.0.1:8080 in your browser)
- stop the program with Control + C
- done, valgrind should output `definitely lost: 15 bytes in 1 blocks` in its leak summary if your `Accept-Language` header is set to `"en-US,en;q=0.5"`, otherwise the size may be different.

The number of bytes and the number of blocks shall multiply by the number of requests you make (given that your `Accept-Language` header stays the same).

**Comment by AlysonBelle** [comment]
I'm not sure if this issue's still open, but after reading the source code it seems like `onion_request_get_language_code(req)` makes a call to `strdup` which allocates its bytes.
The reason it would be leaking after each run is because inside the print statement, `onion_request_get_language_code(req)` is malloced but has no chance to ever be freed.

I ran it like this
```
char *value = onion_request_get_language_code(req);
ONION_INFO("%s", value);
free(value);
```
and my leak count is 0.

I don't know if this is the issue or perhaps I'm not understanding something?

**Comment by ofiala-a51** [comment]
Hello,

thank you, this seems to be the issue. Also, it turns out that the main issue is my inability to read as this need to free the result is described in the documentation as well.

I'm really sorry for wasting your time.

Best Regards,
Ondřej Fiala
